from dataclasses import dataclass
from enum import Enum

@dataclass
class skin:
	@property
	def skin_name(self) -> str:
		return f"{self.weapon_type} | {self.finish_name}"

	finish_name: str
	weapon_type: weapon_type
	collection_name: collection
	min_float: float
	max_float: float
	float_value: float
	rarity: rarity 

class weapon_type(Enum):
	DesertEagle = "weapon_deagle"
	DualBerettas = "weapon_elite"
	FiveSeven = "weapon_fiveseven"
	Glock18 = "weapon_glock"
	P2000 = "weapon_hkp2000"
	P250 = "weapon_p250"
	USP_S = "weapon_usp_silencer"
	CZ75Auto = "weapon_cz75a"
	R8Revolver = "weapon_revolver"
	Tec9 = "weapon_tec9"
	Mac10 = "weapon_mac10"
	MP5SD = "weapon_mp5sd"
	MP7 = "weapon_mp7"
	MP9 = "weapon_mp9"
	P90 = "weapon_p90"
	PPBizon = "weapon_bizon"
	UMP45 = "weapon_ump45"
	AK47 = "weapon_ak47"
	Aug = "weapon_aug"
	Famas = "weapon_famas"
	Galil = "weapon_galilar"
	M4A1 = "weapon_m4a1"
	M4A1_S = "weapon_m4a1_silencer"
	SG556 = "weapon_sg556"
	AWP = "weapon_awp"
	G3SG1 = "weapon_g3sg1"
	Scar20 = "weapon_scar20"
	M249 = "weapon_m249"
	Negev = "weapon_negev"
	Nova = "weapon_nova"
	SawedOff = "weapon_sawedoff"
	Mag7 = "weapon_mag7"
	XM1014 = "weapon_xm1014"
	Bayonet = "weapon_bayonet"
	FlipKnife = "weapon_knife_flip"
	GutKnife = "weapon_knife_gut"
	Karambit = "weapon_knife_karambit"
	M9Bayonet = "weapon_knife_m9_bayonet"
	HuntsmanKnife = "weapon_knife_tactical"
	FalchionKnife = "weapon_knife_falchion"
	BowieKnife = "weapon_knife_survival_bowie"
	ButterflyKnife = "weapon_knife_butterfly"
	ShaddowDaggers = "weapon_knife_push"
	ParacordKnife = "weapon_knife_cord"
	SurvivalKnife = "weapon_knife_canis"
	UrsusKnife = "weapon_knife_ursus"
	NajavaKnife = "weapon_knife_gypsy_jackknife"
	NomadKnife = "weapon_knife_outdoor"
	StilettoKnife = "weapon_knife_stiletto"
	TalonKnife = "weapon_knife_widowmaker"
	SkeletonKnife = "weapon_knife_skeleton"
	ClassKnife = "weapon_knife_css"
	Zeus = "weapon_taser"

class rarity(Enum):
	consumer = 1
	industrial = 2
	milspec = 3
	restricted = 4
	classified = 5
	covert = 6
	gold = 7 

class collection(Enum):
	TheDustCollection = "set_dust"
	TheAztecCollection = "set_aztec"
	TheVertigoCollection = "set_vertigo"
	TheInfernoCollection = "set_inferno"
	TheMilitiaCollection = "set_militia"
	TheNukeCollection = "set_nuke"
	TheOfficeCollection = "set_office"
	TheAssaultCollection = "set_assault"
	TheDust2Collection = "set_dust_2"
	TheTrainCollection = "set_train"
	TheMirageCollection = "set_mirage"
	TheItalyCollection = "set_italy"
	TheLakeCollection = "set_lake"
	TheSafehouseCollection = "set_safehouse"
	TheESports2013Collection = "set_esports"
	TheArmsDealCollection = "set_weapons_i"
	TheBravoCollection = "set_bravo_i"
	TheAlphaCollection = "set_bravo_ii"
	TheArmsDeal2Collection = "set_weapons_ii"
	TheESports2013WinterCollection = "set_esports_ii"
	TheESports2014SummerCollection = "set_esports_iii"
	TheWinterOffensiveCollection = "set_community_1"
	TheArmsDeal3Collection = "set_weapons_iii"
	ThePhoenixCollection = "set_community_2"
	TheHuntsmanCollection = "set_community_3"
	TheBreakoutCollection = "set_community_4"
	TheVanguardCollection = "set_community_5"
	TheChromaCollection = "set_community_6"
	TheChroma2Collection = "set_community_7"
	TheFalchionCollection = "set_community_8"
	TheShadowCollection = "set_community_9"
	TheBankCollection = "set_bank"
	TheBaggageCollection = "set_baggage"
	TheCobblestoneCollection = "set_cobblestone"
	TheOverpassCollection = "set_overpass"
	TheCacheCollection = "set_cache"
	TheGodsAndMonstersCollection = "set_gods_and_monsters"
	TheChopShopCollection = "set_chopshop"
	TheRisingSunCollection = "set_kimono"
	TheRevolverCaseCollection = "set_community_10"
	TheWildfireCollection = "set_community_11"
	TheChroma3Collection = "set_community_12"
	TheGammaCollection = "set_community_13"
	TheGamma2Collection = "set_Gamma_2"
	TheGloveCollection = "set_community_15"
	TheSpectrumCollection = "set_community_16"
	TheOperationHydraCollection = "set_community_17"
	TheSpectrum2Collection = "set_community_18"
	TheClutchCollection = "set_community_19"
	TheHorizonCollection = "set_community_20"
	TheCanalsCollection = "set_canals"
	TheStMarcCollection = "set_stmarc"
	The2018InfernoCollection = "set_inferno_2"
	TheNorseCollection = "set_norse"
	The2018NukeCollection = "set_nuke_2"
	TheDangerZoneCollection = "set_community_21"
	TheXRayCollection = "set_xraymachine"
	TheBlacksiteCollection = "set_blacksite"
	ThePrismaCollection = "set_community_22"
	TheShatteredWebCollection = "set_community_23"
	TheCS20Collection = "set_community_24"
	The2021Dust2Collection = "set_dust_2_2021"
	The2021MirageCollection = "set_mirage_2021"
	ThePrisma2Collection = "set_community_25"
	TheFractureCollection = "set_community_26"
	TheOperationBrokenFangCollection = "set_community_27"
	TheControlCollection = "set_op10_ct"
	TheHavocCollection = "set_op10_t"
	TheAncientCollection = "set_op10_ancient"
	TheSnakebiteCollection = "set_community_28"
	The2021TrainCollection = "set_train_2021"
	The2021VertigoCollection = "set_vertigo_2021"
	TheOperationRiptideCollection = "set_community_29"
	TheDreamsAndNightmaresCollection = "set_community_30"
	TheRecoilCollection = "set_community_31"
	TheRevolutionCollection = "set_community_32"
	TheKilowattCollection = "set_community_33"
	TheAnubisCollection = "set_anubis"
	TheGraphicDesignCollection = "set_graphic_design"
	TheOverpass2024Collection = "set_overpass_2024"
	TheSportAndFieldCollection = "set_realism_camo"
	LimitedEditionItem = "set_xpshop_wpn_01"
	TheGalleryCollection = "set_community_34"
	TheFeverCollection = "set_community_35"
	TheTrain2025Collection = "set_train_2025"
	TheRadiantCollection = "set_timed_drops_warm"
	TheBorealCollection = "set_timed_drops_neutral"
	TheAscentCollection = "set_timed_drops_cool"
	TheGenesisCollection = "set_community_36"
	TheHarlequinCollection = "set_timed_drops_exuberant"
	TheAchromaCollection = "set_timed_drops_achroma"
	OperationRiptideAgents = "set_op11_characters"
	BrokenFangAgents = "set_op10_characters"
	ShatteredWebAgents = "set_op9_characters"